-- CreateTable
CREATE TABLE `Books` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `author` VARCHAR(191) NOT NULL,
    `genre` ENUM('FICTION', 'NONFICTION', 'MYSTERY', 'SCIFI', 'FANTASY', 'BIOGRAPHY', 'HISTORY', 'ROMANCE') NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
