-- AlterTable
ALTER TABLE `Books` ADD COLUMN `description` TEXT NULL,
    MODIFY `genre` ENUM('FICTION', 'NONFICTION', 'MYSTERY', 'SCIFI', 'FANTASY', 'BIOGRAPHY', 'HISTORY', 'ROMANCE', 'THRILLER', 'HORROR', 'SELFHELP', 'PHILOSOPHY', 'POETRY', 'BUSINESS', 'TRAVEL', 'HEALTH', 'SCIENCE', 'RELIGION', 'CHILDREN', 'EDUCATION') NOT NULL;
